version: "2.0"

services:

  # ----------------------------------------
  # Backstage UI
  # ----------------------------------------

  backstage:
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    environment:
     - "SOLR_URL=http://warc-solr:8983/solr/discovery"
    ports:
     - 3000:3000


  # ----------------------------------------
  # Solr instances for running tests against
  # ----------------------------------------

  warc-solr:
    image: ukwa/webarchive-discovery-solr
    ports:
      - 8984:8983

