version: "2.0"

services:

  # Solr content instance for running tests against
  warc-solr:
    image: ukwa/webarchive-discovery-solr
    ports:
      - 8984:8983

  trackdb:
    image: solr:7.7-slim
    ports:
      - 8983:8983
    volumes:
      - ./docker/trackdb/var:/var/solr
      - ./docker/trackdb/mycores:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - tracking

  # Backstage UI
  backstage:
    build: .
    environment:
     - "SOLR_URL=http://solr:8983/solr/discovery"
     - "TRACKDB_SOLR_URL=http://trackdb:8983/solr/tracking"
    ports:
     - 3000:3000


